FROM node:20-alpine

WORKDIR /usr/src/app

RUN npm install -g npm@latest

COPY package.json .
COPY package-lock.json ./

RUN npm install -g npm@11.4.2

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]