services:
  postgres:
    image: "postgres:17.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_USERNAME: "test"
      DB_PASSWORD: "test"
      DB_DATABASE: "test"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
  
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data: